[package]
name = "aerospike"
version = "1.2.0"
edition = "2021"
description = "Aerospike Client for Rust"
keywords = ["aerospike", "nosql", "distributed", "database"]
categories = ["database"]
homepage = "https://www.aerospike.com/"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
log = "0.4.17"
byteorder = "1.4.3"
ripemd = "0.1.3"
base64 = "0.21.0"
crossbeam-queue = "0.3.8"
rand = "0.8.5"
error-chain = "0.12.4"
pwhash = "1.0.0"
serde = { version = "1.0.152", features = ["derive"], optional = true }
futures = { version = "0.3.26" }
async-trait = "0.1.64"
tokio = { version = "1.25.0", features = ["fs", "io-util", "net", "rt", "sync", "time"] }
once_cell = "1.17.1"

[features]
default = []
serialization = ["dep:serde"]

[dev-dependencies]
env_logger = "0.10.0"
hex = "0.4.3"
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["macros"] }
