[package]
name = "aerospike"
version = "1.2.0"
edition = "2021"
description = "Aerospike Client for Rust"
keywords = ["aerospike", "nosql", "distributed", "database"]
categories = ["database"]
homepage = "https://www.aerospike.com/"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
async-trait = "0.1.64"
base64 = "0.21.0"
byteorder = "1.4.3"
crossbeam-queue = "0.3.8"
futures-executor = "0.3.26"
once_cell = "1.17.1"
pwhash = "1.0.0"
rand = "0.8.5"
ripemd = "0.1.3"
serde = { version = "1.0.152", features = ["derive"], optional = true }
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["fs", "io-util", "net", "rt", "sync", "time"] }
tracing = "0.1.37"

[features]
default = []
serialization = ["dep:serde"]

[dev-dependencies]
hex = "0.4.3"
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
