[package]
name = "aerospike"
version = "1.2.0"
edition = "2021"
description = "Aerospike Client for Rust"
keywords = ["aerospike", "nosql", "distributed", "database"]
categories = ["database"]
homepage = "https://www.aerospike.com/"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
log = "0.4"
byteorder = "1.3"
ripemd160 = "0.8"
base64 = "0.21.0"
crossbeam-queue = "0.3.8"
rand = "0.8.5"
lazy_static = "1.4"
error-chain = "0.12"
pwhash = "0.3"
serde = { version = "1.0", features = ["derive"], optional = true }
futures = { version = "0.3.16" }
async-trait = "0.1.51"
tokio = { version = "1.25.0", features = ["fs", "sync", "time"] }


[features]
default = []
serialization = ["dep:serde"]

[dev-dependencies]
env_logger = "0.7"
hex = "0.4"
serde_json = "1.0"
rand = "0.7"
lazy_static = "1.4"
futures = { version = "0.3.16" }
tokio = { version = "1.10.0", features = ["full"] }
