[licenses]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip = [
    { name = "bitflags", version = "=1.3.2" },
    { name = "regex-syntax", version = "=0.6.29" },
]
