name: CI
on: [pull_request, push]
env:
  RUSTFLAGS: "-C debuginfo=0 -D warnings"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, "1.62"]
    services:
      aerospike:
        image: aerospike/aerospike-server
        options: >-
          --health-cmd "test $(asinfo -v namespaces) = 'test'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3000:3000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Run rustfmt
        run: cargo fmt -- --check
      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check ${{ matrix.checks }}
        uses: dnaka91/actions/deny-check@main
        with:
          checks: ${{ matrix.checks }}
